### PR TITLE
Ohm content migrations

### PR DESCRIPTION
**Pull request by jeffreyameyer**
Here you go... please let me know what looks right and wrong!

### CODE REVIEW

**Comment by jeffreyameyer** [comment]
https://github.com/OpenHistoricalMap/issues/issues/150

**Comment by jeffreyameyer** [comment]
Holding off on any merge, pending @geohacker, @batpad, @rub21, or @danrademacher review.

**Review by geohacker — CHANGES_REQUESTED** [review]
@jeffreyameyer Thank you! The changes look good, but I don't think we should remove locales from this repository. They are referenced from the [internationalization.js](https://github.com/OpenHistoricalMap/tasking-manager/blob/ohm_content_migrations/frontend/src/utils/internationalization.js#L1) script and would require us to update that. 

I recommend that we point all the locales to en.json in the internationalization script instead of removing these files. At a later stage, we can incorporate translations.

**Comment by geohacker** [comment]
I think the next steps here should be:
* [ ] @jeffreyameyer add back the deleted locales. Or revert the commit
* [ ] @jeffreyameyer ensure the changes to en.json are pushed
* [ ] @geohacker update internationalization.js
* [ ] Deploy to staging

**Comment by jeffreyameyer** [comment]
Added back the missing locale files.
Confirmed correct file at: https://github.com/OpenHistoricalMap/tasking-manager/blob/ohm_content_migrations/frontend/src/locales/en.json

**Pull request merged**
